# Docker compose: https://docs.docker.com/compose/  YAML: https://yaml.org/spec/1.2.2/
name: dbbe_project_new

services:
  siba_db_service:
    image: mariadb:latest
    container_name: siba_db_container_new
    env_file:
      - .env
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - ./Database/SQL_Scripts/000__CreateALLdb.sql:/docker-entrypoint-initdb.d/init.sql
      - mariadb_data:/var/lib/mysql  # Leave as mariadb_data
    networks:
      - db_be_network

  siba_be_service:
    container_name: siba_be_container_new
    build: .
    env_file: 
     - .env
    depends_on:
      - siba_db_service  # Fixed the typo here
    environment:
      - DB_HOST=siba_db_service  # Fixed to match the correct service name
    ports:
      - '${BE_SERVER_PORT}:${BE_SERVER_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - db_be_network

networks:
  db_be_network:
    driver: bridge

volumes:
  mariadb_data:  # Change to mariadb_data for consistency
